### ISSUE TITLE
Unable to change logo immediately after uploading an initial logo

### ISSUE THREAD

**Issue by davebaiocchi** [sos-bend/web#39] opened 2020-04-09 03:27 UTC
During merchant claiming process, step four is Upload a logo. Let's sat I do that. Then let's say I immediately change my mind and want to upload a new logo. Clicking on the Change button, I can select a new file to upload, hit OK, and the dialog closes, but then nothing happens. The original logo remains.

**Comment by spolitakis** [comment] 2020-04-09 13:36
duplicate of #9

**Closed by spolitakis** 2020-04-09 13:36 UTC
Labels: duplicate
