### ISSUE TITLE
Linked pages not functioning

### ISSUE THREAD

**Issue by mattabrams** [sos-bend/web#27] opened 2020-04-08 22:15 UTC
![Screen Shot 2020-04-08 at 15 15 35](https://user-images.githubusercontent.com/28972351/78838817-d5b50400-79ab-11ea-9365-9a1f24ca03be.png)

**Comment by spolitakis** [comment] 2020-04-09 03:10
duplicate of #35

**Closed by spolitakis** 2020-04-09 03:10 UTC
